FROM priyatam19/compiler-opts-lli-stats:llvm21
RUN apt-get update && apt-get install -y --no-install-recommends \
    libxml2 qemu-user qemu-user-static \
    gcc-riscv64-linux-gnu libc6-dev-riscv64-cross \
    libzstd-dev zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*
